base_model = "xiaomi/mimo-v2-flash"
reasoning_options = [{ type = "toggle" }]
name = "MiMo V2 Flash"
release_date = "2025-12-17"
knowledge = "2024-10"
open_weights = false

[cost]
input = 0.1
output = 0.3
cache_read = 0.01

[limit]
output = 32_000
