name = "Qwen3 Max (2026-01-23)"
family = "qwen"
release_date = "2026-01-23"
last_updated = "2026-01-23"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.359
output = 1.434
cache_read = 0.072

[limit]
context = 256_000
output = 32_800

[modalities]
input = ["text", "image"]
output = ["text"]
