base_model = "zhipuai/glm-4.7-flash"
reasoning_options = [{ type = "toggle" }]
name = "GLM 4.7 Flash"
family = "glm"
release_date = "2026-03-13"
open_weights = false

[cost]
input = 0.07
output = 0.4

[limit]
output = 131_000
