base_model = "openai/o3-pro"
reasoning_options = [{ type = "effort", values = ["low", "medium", "high"] }]
name = "o3 Pro"
release_date = "2025-04-16"
temperature = true
knowledge = "2024-10"

[cost]
input = 20
output = 80

[limit]
input = 100_000

[modalities]
input = ["text", "image", "pdf"]
